name: Build

# Triggers the workflow on push or pull request events (for any branch in a repository)
on: [ push, pull_request ]

jobs:
  # tests the NixOS/list-nixos-options.sh script
  print_nixos_opts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - run: ./NixOS/list-nixos-options.sh

  # Tests that a configuration.nix can include common NixOS modules.
  test_nixos_cfg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: ./NixOS/_test/test-build.sh
