name: Build

# Triggers the workflow on push or pull request events (for any branch in a repository)
on: [ push, pull_request, merge_group ]

jobs:
  # tests the NixOS/list-nixos-options.sh script
  print_nixos_opts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: ./NixOS/list-nixos-options.sh

  # Tests that a configuration.nix can include common NixOS modules.
  test_nixos_cfg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: ./NixOS/_test/test-build.sh

  # Tests that a configuration.nix can include common NixOS modules.
  check_nixos_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt NixOS --check"
